/*==============================================================*/
/* DBMS name:      MySQL 5.0                                    */
/* Created on:     10/16/2017 7:21:08 PM                        */
/*==============================================================*/


drop table if exists AGENDA;

drop table if exists JARAK;

drop table if exists KOTA;

drop table if exists LOKASI;

drop table if exists MODE_TRANSPORTASI;

drop table if exists PERJALANAN;

drop table if exists PROVINSI;

drop table if exists TRAVELLER;

/*==============================================================*/
/* Table: AGENDA                                                */
/*==============================================================*/
create table AGENDA
(
   ID_TRAVELLER         bigint not null,
   KD_PROVINSI          char(2) not null,
   KD_KOTA              char(2) not null,
   ID_LOKASI            int not null,
   ID_AGENDA            bigint not null,
   NM_AGENDA            varchar(35) not null,
   WAKTU_MULAI_AGENDA   datetime not null,
   WAKTU_BERAKHIR_AGENDA datetime not null,
   CATATAN              text,
   TEMPAT               varchar(25),
   primary key (ID_TRAVELLER, KD_PROVINSI, KD_KOTA, ID_LOKASI, ID_AGENDA)
);

/*==============================================================*/
/* Table: JARAK                                                 */
/*==============================================================*/
create table JARAK
(
   KD_PROVINSI_AKHIR    char(2) not null,
   KD_KOTA_AKHIR        char(2) not null,
   ID_LOKASI_AKHIR      int not null,
   KD_PROVINSI_AWAL     char(2) not null,
   KD_KOTA_AWAL         char(2) not null,
   ID_LOKASI_AWAL       int not null,
   JARAK                float,
   primary key (KD_PROVINSI_AKHIR, KD_KOTA_AKHIR, ID_LOKASI_AKHIR, KD_PROVINSI_AWAL, KD_KOTA_AWAL, ID_LOKASI_AWAL)
);

/*==============================================================*/
/* Table: KOTA                                                  */
/*==============================================================*/
create table KOTA
(
   KD_KOTA		char(2) not null,
   KD_PROVINSI      	char(2) not null,
   NM_KOTA          	varchar(30),
   primary key (KD_PROVINSI, KD_KOTA)
);

/*==============================================================*/
/* Table: LOKASI                                                */
/*==============================================================*/
create table LOKASI
(
   KD_PROVINSI          char(2) not null,
   KD_KOTA              char(2) not null,
   ID_LOKASI            int not null,
   ALAMAT_TEMPAT        varchar(55),
   primary key (KD_PROVINSI, KD_KOTA, ID_LOKASI)
);

/*==============================================================*/
/* Table: MODE_TRANSPORTASI                                     */
/*==============================================================*/
create table MODE_TRANSPORTASI
(
   KD_MODA_TRANSPORTASI char(2) not null,
   NAMA_TRANSPORTASI    varchar(30),
   KECEPATAN            float,
   primary key (KD_MODA_TRANSPORTASI)
);

/*==============================================================*/
/* Table: PERJALANAN                                            */
/*==============================================================*/
create table PERJALANAN
(
   KD_MODA_TRANSPORTASI char(2) not null,
   ID_TRAVELLER         bigint not null,
   KD_PROVINSI          char(2) not null,
   KD_KOTA              char(2) not null,
   ID_LOKASI            int not null,
   ID_AGENDA            bigint not null,
   DEPATURE_TIME        datetime,
   primary key (ID_TRAVELLER, KD_PROVINSI, KD_KOTA, ID_LOKASI, KD_MODA_TRANSPORTASI, ID_AGENDA)
);

/*==============================================================*/
/* Table: PROVINSI                                              */
/*==============================================================*/
create table PROVINSI
(
   KD_PROVINSI          char(2) not null,
   NM_PROVINSI          varchar(30),
   primary key (KD_PROVINSI)
);

/*==============================================================*/
/* Table: TRAVELLER                                             */
/*==============================================================*/
create table TRAVELLER
(
   ID_TRAVELLER         bigint not null,
   NM_PENGGUNA          varchar(20),
   ALAMAT_EMAIL         varchar(40),
   KATA_SANDI           varchar(25),
   NAMA_LENGKAP         varchar(30),
   primary key (ID_TRAVELLER)
);

alter table AGENDA add constraint FK_BERLOKASI foreign key (KD_PROVINSI, KD_KOTA, ID_LOKASI)
      references LOKASI (KD_PROVINSI, KD_KOTA, ID_LOKASI) on delete restrict on update restrict;

alter table AGENDA add constraint FK_MEMBUAT foreign key (ID_TRAVELLER)
      references TRAVELLER (ID_TRAVELLER) on delete restrict on update restrict;

alter table JARAK add constraint FK_LOKASI_1 foreign key (KD_PROVINSI_AKHIR, KD_KOTA_AKHIR, ID_LOKASI_AKHIR)
      references LOKASI (KD_PROVINSI, KD_KOTA, ID_LOKASI) on delete restrict on update restrict;

alter table JARAK add constraint FK_LOKASI_2 foreign key (KD_PROVINSI_AWAL, KD_KOTA_AWAL, ID_LOKASI_AWAL)
      references LOKASI (KD_PROVINSI, KD_KOTA, ID_LOKASI) on delete restrict on update restrict;

alter table KOTA add constraint FK_MEMILIKI_KO_PR foreign key (KD_PROVINSI)
      references PROVINSI (KD_PROVINSI) on delete restrict on update restrict;

alter table LOKASI add constraint FK_MEMILIKI_KO_LO foreign key (KD_PROVINSI, KD_KOTA)
      references KOTA (KD_PROVINSI, KD_KOTA) on delete restrict on update restrict;

alter table PERJALANAN add constraint FK_MEMBUTUHKAN foreign key (KD_MODA_TRANSPORTASI)
      references MODE_TRANSPORTASI (KD_MODA_TRANSPORTASI) on delete restrict on update restrict;

alter table PERJALANAN add constraint FK_MEMILIKI_PE_AG foreign key (ID_TRAVELLER, KD_PROVINSI, KD_KOTA, ID_LOKASI, ID_AGENDA)
      references AGENDA (ID_TRAVELLER, KD_PROVINSI, KD_KOTA, ID_LOKASI, ID_AGENDA) on delete restrict on update restrict;

INSERT INTO `kota` VALUES ('01', '11', 'KABUPATEN SIMEULUE');
INSERT INTO `kota` VALUES ('02', '11', 'KABUPATEN ACEH SINGKIL');
INSERT INTO `kota` VALUES ('03', '11', 'KABUPATEN ACEH SELATAN');
INSERT INTO `kota` VALUES ('04', '11', 'KABUPATEN ACEH TENGGARA');
INSERT INTO `kota` VALUES ('05', '11', 'KABUPATEN ACEH TIMUR');
INSERT INTO `kota` VALUES ('06', '11', 'KABUPATEN ACEH TENGAH');
INSERT INTO `kota` VALUES ('07', '11', 'KABUPATEN ACEH BARAT');
INSERT INTO `kota` VALUES ('08', '11', 'KABUPATEN ACEH BESAR');
INSERT INTO `kota` VALUES ('09', '11', 'KABUPATEN PIDIE');
INSERT INTO `kota` VALUES ('10', '11', 'KABUPATEN BIREUEN');
INSERT INTO `kota` VALUES ('11', '11', 'KABUPATEN ACEH UTARA');
INSERT INTO `kota` VALUES ('12', '11', 'KABUPATEN ACEH BARAT DAYA');
INSERT INTO `kota` VALUES ('13', '11', 'KABUPATEN GAYO LUES');
INSERT INTO `kota` VALUES ('14', '11', 'KABUPATEN ACEH TAMIANG');
INSERT INTO `kota` VALUES ('15', '11', 'KABUPATEN NAGAN RAYA');
INSERT INTO `kota` VALUES ('16', '11', 'KABUPATEN ACEH JAYA');
INSERT INTO `kota` VALUES ('17', '11', 'KABUPATEN BENER MERIAH');
INSERT INTO `kota` VALUES ('18', '11', 'KABUPATEN PIDIE JAYA');
INSERT INTO `kota` VALUES ('71', '11', 'KOTA BANDA ACEH');
INSERT INTO `kota` VALUES ('72', '11', 'KOTA SABANG');
INSERT INTO `kota` VALUES ('73', '11', 'KOTA LANGSA');
INSERT INTO `kota` VALUES ('74', '11', 'KOTA LHOKSEUMAWE');
INSERT INTO `kota` VALUES ('75', '11', 'KOTA SUBULUSSALAM');
INSERT INTO `kota` VALUES ('01', '12', 'KABUPATEN NIAS');
INSERT INTO `kota` VALUES ('02', '12', 'KABUPATEN MANDAILING NATAL');
INSERT INTO `kota` VALUES ('03', '12', 'KABUPATEN TAPANULI SELATAN');
INSERT INTO `kota` VALUES ('04', '12', 'KABUPATEN TAPANULI TENGAH');
INSERT INTO `kota` VALUES ('05', '12', 'KABUPATEN TAPANULI UTARA');
INSERT INTO `kota` VALUES ('06', '12', 'KABUPATEN TOBA SAMOSIR');
INSERT INTO `kota` VALUES ('07', '12', 'KABUPATEN LABUHAN BATU');
INSERT INTO `kota` VALUES ('08', '12', 'KABUPATEN ASAHAN');
INSERT INTO `kota` VALUES ('09', '12', 'KABUPATEN SIMALUNGUN');
INSERT INTO `kota` VALUES ('10', '12', 'KABUPATEN DAIRI');
INSERT INTO `kota` VALUES ('11', '12', 'KABUPATEN KARO');
INSERT INTO `kota` VALUES ('12', '12', 'KABUPATEN DELI SERDANG');
INSERT INTO `kota` VALUES ('13', '12', 'KABUPATEN LANGKAT');
INSERT INTO `kota` VALUES ('14', '12', 'KABUPATEN NIAS SELATAN');
INSERT INTO `kota` VALUES ('15', '12', 'KABUPATEN HUMBANG HASUNDUTAN');
INSERT INTO `kota` VALUES ('16', '12', 'KABUPATEN PAKPAK BHARAT');
INSERT INTO `kota` VALUES ('17', '12', 'KABUPATEN SAMOSIR');
INSERT INTO `kota` VALUES ('18', '12', 'KABUPATEN SERDANG BEDAGAI');
INSERT INTO `kota` VALUES ('19', '12', 'KABUPATEN BATU BARA');
INSERT INTO `kota` VALUES ('20', '12', 'KABUPATEN PADANG LAWAS UTARA');
INSERT INTO `kota` VALUES ('21', '12', 'KABUPATEN PADANG LAWAS');
INSERT INTO `kota` VALUES ('22', '12', 'KABUPATEN LABUHAN BATU SELATAN');
INSERT INTO `kota` VALUES ('23', '12', 'KABUPATEN LABUHAN BATU UTARA');
INSERT INTO `kota` VALUES ('24', '12', 'KABUPATEN NIAS UTARA');
INSERT INTO `kota` VALUES ('25', '12', 'KABUPATEN NIAS BARAT');
INSERT INTO `kota` VALUES ('71', '12', 'KOTA SIBOLGA');
INSERT INTO `kota` VALUES ('72', '12', 'KOTA TANJUNG BALAI');
INSERT INTO `kota` VALUES ('73', '12', 'KOTA PEMATANG SIANTAR');
INSERT INTO `kota` VALUES ('74', '12', 'KOTA TEBING TINGGI');
INSERT INTO `kota` VALUES ('75', '12', 'KOTA MEDAN');
INSERT INTO `kota` VALUES ('76', '12', 'KOTA BINJAI');
INSERT INTO `kota` VALUES ('77', '12', 'KOTA PADANGSIDIMPUAN');
INSERT INTO `kota` VALUES ('78', '12', 'KOTA GUNUNGSITOLI');
INSERT INTO `kota` VALUES ('01', '13', 'KABUPATEN KEPULAUAN MENTAWAI');
INSERT INTO `kota` VALUES ('02', '13', 'KABUPATEN PESISIR SELATAN');
INSERT INTO `kota` VALUES ('03', '13', 'KABUPATEN SOLOK');
INSERT INTO `kota` VALUES ('04', '13', 'KABUPATEN SIJUNJUNG');
INSERT INTO `kota` VALUES ('05', '13', 'KABUPATEN TANAH DATAR');
INSERT INTO `kota` VALUES ('06', '13', 'KABUPATEN PADANG PARIAMAN');
INSERT INTO `kota` VALUES ('07', '13', 'KABUPATEN AGAM');
INSERT INTO `kota` VALUES ('08', '13', 'KABUPATEN LIMA PULUH KOTA');
INSERT INTO `kota` VALUES ('09', '13', 'KABUPATEN PASAMAN');
INSERT INTO `kota` VALUES ('10', '13', 'KABUPATEN SOLOK SELATAN');
INSERT INTO `kota` VALUES ('11', '13', 'KABUPATEN DHARMASRAYA');
INSERT INTO `kota` VALUES ('12', '13', 'KABUPATEN PASAMAN BARAT');
INSERT INTO `kota` VALUES ('71', '13', 'KOTA PADANG');
INSERT INTO `kota` VALUES ('72', '13', 'KOTA SOLOK');
INSERT INTO `kota` VALUES ('73', '13', 'KOTA SAWAH LUNTO');
INSERT INTO `kota` VALUES ('74', '13', 'KOTA PADANG PANJANG');
INSERT INTO `kota` VALUES ('75', '13', 'KOTA BUKITTINGGI');
INSERT INTO `kota` VALUES ('76', '13', 'KOTA PAYAKUMBUH');
INSERT INTO `kota` VALUES ('77', '13', 'KOTA PARIAMAN');
INSERT INTO `kota` VALUES ('01', '14', 'KABUPATEN KUANTAN SINGINGI');
INSERT INTO `kota` VALUES ('02', '14', 'KABUPATEN INDRAGIRI HULU');
INSERT INTO `kota` VALUES ('03', '14', 'KABUPATEN INDRAGIRI HILIR');
INSERT INTO `kota` VALUES ('04', '14', 'KABUPATEN PELALAWAN');
INSERT INTO `kota` VALUES ('05', '14', 'KABUPATEN S I A K');
INSERT INTO `kota` VALUES ('06', '14', 'KABUPATEN KAMPAR');
INSERT INTO `kota` VALUES ('07', '14', 'KABUPATEN ROKAN HULU');
INSERT INTO `kota` VALUES ('08', '14', 'KABUPATEN BENGKALIS');
INSERT INTO `kota` VALUES ('09', '14', 'KABUPATEN ROKAN HILIR');
INSERT INTO `kota` VALUES ('10', '14', 'KABUPATEN KEPULAUAN MERANTI');
INSERT INTO `kota` VALUES ('71', '14', 'KOTA PEKANBARU');
INSERT INTO `kota` VALUES ('73', '14', 'KOTA D U M A I');
INSERT INTO `kota` VALUES ('01', '15', 'KABUPATEN KERINCI');
INSERT INTO `kota` VALUES ('02', '15', 'KABUPATEN MERANGIN');
INSERT INTO `kota` VALUES ('03', '15', 'KABUPATEN SAROLANGUN');
INSERT INTO `kota` VALUES ('04', '15', 'KABUPATEN BATANG HARI');
INSERT INTO `kota` VALUES ('05', '15', 'KABUPATEN MUARO JAMBI');
INSERT INTO `kota` VALUES ('06', '15', 'KABUPATEN TANJUNG JABUNG TIMUR');
INSERT INTO `kota` VALUES ('07', '15', 'KABUPATEN TANJUNG JABUNG BARAT');
INSERT INTO `kota` VALUES ('08', '15', 'KABUPATEN TEBO');
INSERT INTO `kota` VALUES ('09', '15', 'KABUPATEN BUNGO');
INSERT INTO `kota` VALUES ('71', '15', 'KOTA JAMBI');
INSERT INTO `kota` VALUES ('72', '15', 'KOTA SUNGAI PENUH');
INSERT INTO `kota` VALUES ('01', '16', 'KABUPATEN OGAN KOMERING ULU');
INSERT INTO `kota` VALUES ('02', '16', 'KABUPATEN OGAN KOMERING ILIR');
INSERT INTO `kota` VALUES ('03', '16', 'KABUPATEN MUARA ENIM');
INSERT INTO `kota` VALUES ('04', '16', 'KABUPATEN LAHAT');
INSERT INTO `kota` VALUES ('05', '16', 'KABUPATEN MUSI RAWAS');
INSERT INTO `kota` VALUES ('06', '16', 'KABUPATEN MUSI BANYUASIN');
INSERT INTO `kota` VALUES ('07', '16', 'KABUPATEN BANYU ASIN');
INSERT INTO `kota` VALUES ('08', '16', 'KABUPATEN OGAN KOMERING ULU SELATAN');
INSERT INTO `kota` VALUES ('09', '16', 'KABUPATEN OGAN KOMERING ULU TIMUR');
INSERT INTO `kota` VALUES ('10', '16', 'KABUPATEN OGAN ILIR');
INSERT INTO `kota` VALUES ('11', '16', 'KABUPATEN EMPAT LAWANG');
INSERT INTO `kota` VALUES ('12', '16', 'KABUPATEN PENUKAL ABAB LEMATANG ILIR');
INSERT INTO `kota` VALUES ('13', '16', 'KABUPATEN MUSI RAWAS UTARA');
INSERT INTO `kota` VALUES ('71', '16', 'KOTA PALEMBANG');
INSERT INTO `kota` VALUES ('72', '16', 'KOTA PRABUMULIH');
INSERT INTO `kota` VALUES ('73', '16', 'KOTA PAGAR ALAM');
INSERT INTO `kota` VALUES ('74', '16', 'KOTA LUBUKLINGGAU');
INSERT INTO `kota` VALUES ('01', '17', 'KABUPATEN BENGKULU SELATAN');
INSERT INTO `kota` VALUES ('02', '17', 'KABUPATEN REJANG LEBONG');
INSERT INTO `kota` VALUES ('03', '17', 'KABUPATEN BENGKULU UTARA');
INSERT INTO `kota` VALUES ('04', '17', 'KABUPATEN KAUR');
INSERT INTO `kota` VALUES ('05', '17', 'KABUPATEN SELUMA');
INSERT INTO `kota` VALUES ('06', '17', 'KABUPATEN MUKOMUKO');
INSERT INTO `kota` VALUES ('07', '17', 'KABUPATEN LEBONG');
INSERT INTO `kota` VALUES ('08', '17', 'KABUPATEN KEPAHIANG');
INSERT INTO `kota` VALUES ('09', '17', 'KABUPATEN BENGKULU TENGAH');
INSERT INTO `kota` VALUES ('71', '17', 'KOTA BENGKULU');
INSERT INTO `kota` VALUES ('01', '18', 'KABUPATEN LAMPUNG BARAT');
INSERT INTO `kota` VALUES ('02', '18', 'KABUPATEN TANGGAMUS');
INSERT INTO `kota` VALUES ('03', '18', 'KABUPATEN LAMPUNG SELATAN');
INSERT INTO `kota` VALUES ('04', '18', 'KABUPATEN LAMPUNG TIMUR');
INSERT INTO `kota` VALUES ('05', '18', 'KABUPATEN LAMPUNG TENGAH');
INSERT INTO `kota` VALUES ('06', '18', 'KABUPATEN LAMPUNG UTARA');
INSERT INTO `kota` VALUES ('07', '18', 'KABUPATEN WAY KANAN');
INSERT INTO `kota` VALUES ('08', '18', 'KABUPATEN TULANGBAWANG');
INSERT INTO `kota` VALUES ('09', '18', 'KABUPATEN PESAWARAN');
INSERT INTO `kota` VALUES ('10', '18', 'KABUPATEN PRINGSEWU');
INSERT INTO `kota` VALUES ('11', '18', 'KABUPATEN MESUJI');
INSERT INTO `kota` VALUES ('12', '18', 'KABUPATEN TULANG BAWANG BARAT');
INSERT INTO `kota` VALUES ('13', '18', 'KABUPATEN PESISIR BARAT');
INSERT INTO `kota` VALUES ('71', '18', 'KOTA BANDAR LAMPUNG');
INSERT INTO `kota` VALUES ('72', '18', 'KOTA METRO');
INSERT INTO `kota` VALUES ('01', '19', 'KABUPATEN BANGKA');
INSERT INTO `kota` VALUES ('02', '19', 'KABUPATEN BELITUNG');
INSERT INTO `kota` VALUES ('03', '19', 'KABUPATEN BANGKA BARAT');
INSERT INTO `kota` VALUES ('04', '19', 'KABUPATEN BANGKA TENGAH');
INSERT INTO `kota` VALUES ('05', '19', 'KABUPATEN BANGKA SELATAN');
INSERT INTO `kota` VALUES ('06', '19', 'KABUPATEN BELITUNG TIMUR');
INSERT INTO `kota` VALUES ('71', '19', 'KOTA PANGKAL PINANG');
INSERT INTO `kota` VALUES ('01', '21', 'KABUPATEN KARIMUN');
INSERT INTO `kota` VALUES ('02', '21', 'KABUPATEN BINTAN');
INSERT INTO `kota` VALUES ('03', '21', 'KABUPATEN NATUNA');
INSERT INTO `kota` VALUES ('04', '21', 'KABUPATEN LINGGA');
INSERT INTO `kota` VALUES ('05', '21', 'KABUPATEN KEPULAUAN ANAMBAS');
INSERT INTO `kota` VALUES ('71', '21', 'KOTA B A T A M');
INSERT INTO `kota` VALUES ('72', '21', 'KOTA TANJUNG PINANG');
INSERT INTO `kota` VALUES ('01', '31', 'KABUPATEN KEPULAUAN SERIBU');
INSERT INTO `kota` VALUES ('71', '31', 'KOTA JAKARTA SELATAN');
INSERT INTO `kota` VALUES ('72', '31', 'KOTA JAKARTA TIMUR');
INSERT INTO `kota` VALUES ('73', '31', 'KOTA JAKARTA PUSAT');
INSERT INTO `kota` VALUES ('74', '31', 'KOTA JAKARTA BARAT');
INSERT INTO `kota` VALUES ('75', '31', 'KOTA JAKARTA UTARA');
INSERT INTO `kota` VALUES ('01', '32', 'KABUPATEN BOGOR');
INSERT INTO `kota` VALUES ('02', '32', 'KABUPATEN SUKABUMI');
INSERT INTO `kota` VALUES ('03', '32', 'KABUPATEN CIANJUR');
INSERT INTO `kota` VALUES ('04', '32', 'KABUPATEN BANDUNG');
INSERT INTO `kota` VALUES ('05', '32', 'KABUPATEN GARUT');
INSERT INTO `kota` VALUES ('06', '32', 'KABUPATEN TASIKMALAYA');
INSERT INTO `kota` VALUES ('07', '32', 'KABUPATEN CIAMIS');
INSERT INTO `kota` VALUES ('08', '32', 'KABUPATEN KUNINGAN');
INSERT INTO `kota` VALUES ('09', '32', 'KABUPATEN CIREBON');
INSERT INTO `kota` VALUES ('10', '32', 'KABUPATEN MAJALENGKA');
INSERT INTO `kota` VALUES ('11', '32', 'KABUPATEN SUMEDANG');
INSERT INTO `kota` VALUES ('12', '32', 'KABUPATEN INDRAMAYU');
INSERT INTO `kota` VALUES ('13', '32', 'KABUPATEN SUBANG');
INSERT INTO `kota` VALUES ('14', '32', 'KABUPATEN PURWAKARTA');
INSERT INTO `kota` VALUES ('15', '32', 'KABUPATEN KARAWANG');
INSERT INTO `kota` VALUES ('16', '32', 'KABUPATEN BEKASI');
INSERT INTO `kota` VALUES ('17', '32', 'KABUPATEN BANDUNG BARAT');
INSERT INTO `kota` VALUES ('18', '32', 'KABUPATEN PANGANDARAN');
INSERT INTO `kota` VALUES ('71', '32', 'KOTA BOGOR');
INSERT INTO `kota` VALUES ('72', '32', 'KOTA SUKABUMI');
INSERT INTO `kota` VALUES ('73', '32', 'KOTA BANDUNG');
INSERT INTO `kota` VALUES ('74', '32', 'KOTA CIREBON');
INSERT INTO `kota` VALUES ('75', '32', 'KOTA BEKASI');
INSERT INTO `kota` VALUES ('76', '32', 'KOTA DEPOK');
INSERT INTO `kota` VALUES ('77', '32', 'KOTA CIMAHI');
INSERT INTO `kota` VALUES ('78', '32', 'KOTA TASIKMALAYA');
INSERT INTO `kota` VALUES ('79', '32', 'KOTA BANJAR');
INSERT INTO `kota` VALUES ('01', '33', 'KABUPATEN CILACAP');
INSERT INTO `kota` VALUES ('02', '33', 'KABUPATEN BANYUMAS');
INSERT INTO `kota` VALUES ('03', '33', 'KABUPATEN PURBALINGGA');
INSERT INTO `kota` VALUES ('04', '33', 'KABUPATEN BANJARNEGARA');
INSERT INTO `kota` VALUES ('05', '33', 'KABUPATEN KEBUMEN');
INSERT INTO `kota` VALUES ('06', '33', 'KABUPATEN PURWOREJO');
INSERT INTO `kota` VALUES ('07', '33', 'KABUPATEN WONOSOBO');
INSERT INTO `kota` VALUES ('08', '33', 'KABUPATEN MAGELANG');
INSERT INTO `kota` VALUES ('09', '33', 'KABUPATEN BOYOLALI');
INSERT INTO `kota` VALUES ('10', '33', 'KABUPATEN KLATEN');
INSERT INTO `kota` VALUES ('11', '33', 'KABUPATEN SUKOHARJO');
INSERT INTO `kota` VALUES ('12', '33', 'KABUPATEN WONOGIRI');
INSERT INTO `kota` VALUES ('13', '33', 'KABUPATEN KARANGANYAR');
INSERT INTO `kota` VALUES ('14', '33', 'KABUPATEN SRAGEN');
INSERT INTO `kota` VALUES ('15', '33', 'KABUPATEN GROBOGAN');
INSERT INTO `kota` VALUES ('16', '33', 'KABUPATEN BLORA');
INSERT INTO `kota` VALUES ('17', '33', 'KABUPATEN REMBANG');
INSERT INTO `kota` VALUES ('18', '33', 'KABUPATEN PATI');
INSERT INTO `kota` VALUES ('19', '33', 'KABUPATEN KUDUS');
INSERT INTO `kota` VALUES ('20', '33', 'KABUPATEN JEPARA');
INSERT INTO `kota` VALUES ('21', '33', 'KABUPATEN DEMAK');
INSERT INTO `kota` VALUES ('22', '33', 'KABUPATEN SEMARANG');
INSERT INTO `kota` VALUES ('23', '33', 'KABUPATEN TEMANGGUNG');
INSERT INTO `kota` VALUES ('24', '33', 'KABUPATEN KENDAL');
INSERT INTO `kota` VALUES ('25', '33', 'KABUPATEN BATANG');
INSERT INTO `kota` VALUES ('26', '33', 'KABUPATEN PEKALONGAN');
INSERT INTO `kota` VALUES ('27', '33', 'KABUPATEN PEMALANG');
INSERT INTO `kota` VALUES ('28', '33', 'KABUPATEN TEGAL');
INSERT INTO `kota` VALUES ('29', '33', 'KABUPATEN BREBES');
INSERT INTO `kota` VALUES ('71', '33', 'KOTA MAGELANG');
INSERT INTO `kota` VALUES ('72', '33', 'KOTA SURAKARTA');
INSERT INTO `kota` VALUES ('73', '33', 'KOTA SALATIGA');
INSERT INTO `kota` VALUES ('74', '33', 'KOTA SEMARANG');
INSERT INTO `kota` VALUES ('75', '33', 'KOTA PEKALONGAN');
INSERT INTO `kota` VALUES ('76', '33', 'KOTA TEGAL');
INSERT INTO `kota` VALUES ('01', '34', 'KABUPATEN KULON PROGO');
INSERT INTO `kota` VALUES ('02', '34', 'KABUPATEN BANTUL');
INSERT INTO `kota` VALUES ('03', '34', 'KABUPATEN GUNUNG KIDUL');
INSERT INTO `kota` VALUES ('04', '34', 'KABUPATEN SLEMAN');
INSERT INTO `kota` VALUES ('71', '34', 'KOTA YOGYAKARTA');
INSERT INTO `kota` VALUES ('01', '35', 'KABUPATEN PACITAN');
INSERT INTO `kota` VALUES ('02', '35', 'KABUPATEN PONOROGO');
INSERT INTO `kota` VALUES ('03', '35', 'KABUPATEN TRENGGALEK');
INSERT INTO `kota` VALUES ('04', '35', 'KABUPATEN TULUNGAGUNG');
INSERT INTO `kota` VALUES ('05', '35', 'KABUPATEN BLITAR');
INSERT INTO `kota` VALUES ('06', '35', 'KABUPATEN KEDIRI');
INSERT INTO `kota` VALUES ('07', '35', 'KABUPATEN MALANG');
INSERT INTO `kota` VALUES ('08', '35', 'KABUPATEN LUMAJANG');
INSERT INTO `kota` VALUES ('09', '35', 'KABUPATEN JEMBER');
INSERT INTO `kota` VALUES ('10', '35', 'KABUPATEN BANYUWANGI');
INSERT INTO `kota` VALUES ('11', '35', 'KABUPATEN BONDOWOSO');
INSERT INTO `kota` VALUES ('12', '35', 'KABUPATEN SITUBONDO');
INSERT INTO `kota` VALUES ('13', '35', 'KABUPATEN PROBOLINGGO');
INSERT INTO `kota` VALUES ('14', '35', 'KABUPATEN PASURUAN');
INSERT INTO `kota` VALUES ('15', '35', 'KABUPATEN SIDOARJO');
INSERT INTO `kota` VALUES ('16', '35', 'KABUPATEN MOJOKERTO');
INSERT INTO `kota` VALUES ('17', '35', 'KABUPATEN JOMBANG');
INSERT INTO `kota` VALUES ('18', '35', 'KABUPATEN NGANJUK');
INSERT INTO `kota` VALUES ('19', '35', 'KABUPATEN MADIUN');
INSERT INTO `kota` VALUES ('20', '35', 'KABUPATEN MAGETAN');
INSERT INTO `kota` VALUES ('21', '35', 'KABUPATEN NGAWI');
INSERT INTO `kota` VALUES ('22', '35', 'KABUPATEN BOJONEGORO');
INSERT INTO `kota` VALUES ('23', '35', 'KABUPATEN TUBAN');
INSERT INTO `kota` VALUES ('24', '35', 'KABUPATEN LAMONGAN');
INSERT INTO `kota` VALUES ('25', '35', 'KABUPATEN GRESIK');
INSERT INTO `kota` VALUES ('26', '35', 'KABUPATEN BANGKALAN');
INSERT INTO `kota` VALUES ('27', '35', 'KABUPATEN SAMPANG');
INSERT INTO `kota` VALUES ('28', '35', 'KABUPATEN PAMEKASAN');
INSERT INTO `kota` VALUES ('29', '35', 'KABUPATEN SUMENEP');
INSERT INTO `kota` VALUES ('71', '35', 'KOTA KEDIRI');
INSERT INTO `kota` VALUES ('72', '35', 'KOTA BLITAR');
INSERT INTO `kota` VALUES ('73', '35', 'KOTA MALANG');
INSERT INTO `kota` VALUES ('74', '35', 'KOTA PROBOLINGGO');
INSERT INTO `kota` VALUES ('75', '35', 'KOTA PASURUAN');
INSERT INTO `kota` VALUES ('76', '35', 'KOTA MOJOKERTO');
INSERT INTO `kota` VALUES ('77', '35', 'KOTA MADIUN');
INSERT INTO `kota` VALUES ('78', '35', 'KOTA SURABAYA');
INSERT INTO `kota` VALUES ('79', '35', 'KOTA BATU');
INSERT INTO `kota` VALUES ('01', '36', 'KABUPATEN PANDEGLANG');
INSERT INTO `kota` VALUES ('02', '36', 'KABUPATEN LEBAK');
INSERT INTO `kota` VALUES ('03', '36', 'KABUPATEN TANGERANG');
INSERT INTO `kota` VALUES ('04', '36', 'KABUPATEN SERANG');
INSERT INTO `kota` VALUES ('71', '36', 'KOTA TANGERANG');
INSERT INTO `kota` VALUES ('72', '36', 'KOTA CILEGON');
INSERT INTO `kota` VALUES ('73', '36', 'KOTA SERANG');
INSERT INTO `kota` VALUES ('74', '36', 'KOTA TANGERANG SELATAN');
INSERT INTO `kota` VALUES ('01', '51', 'KABUPATEN JEMBRANA');
INSERT INTO `kota` VALUES ('02', '51', 'KABUPATEN TABANAN');
INSERT INTO `kota` VALUES ('03', '51', 'KABUPATEN BADUNG');
INSERT INTO `kota` VALUES ('04', '51', 'KABUPATEN GIANYAR');
INSERT INTO `kota` VALUES ('05', '51', 'KABUPATEN KLUNGKUNG');
INSERT INTO `kota` VALUES ('06', '51', 'KABUPATEN BANGLI');
INSERT INTO `kota` VALUES ('07', '51', 'KABUPATEN KARANG ASEM');
INSERT INTO `kota` VALUES ('08', '51', 'KABUPATEN BULELENG');
INSERT INTO `kota` VALUES ('71', '51', 'KOTA DENPASAR');
INSERT INTO `kota` VALUES ('01', '52', 'KABUPATEN LOMBOK BARAT');
INSERT INTO `kota` VALUES ('02', '52', 'KABUPATEN LOMBOK TENGAH');
INSERT INTO `kota` VALUES ('03', '52', 'KABUPATEN LOMBOK TIMUR');
INSERT INTO `kota` VALUES ('04', '52', 'KABUPATEN SUMBAWA');
INSERT INTO `kota` VALUES ('05', '52', 'KABUPATEN DOMPU');
INSERT INTO `kota` VALUES ('06', '52', 'KABUPATEN BIMA');
INSERT INTO `kota` VALUES ('07', '52', 'KABUPATEN SUMBAWA BARAT');
INSERT INTO `kota` VALUES ('08', '52', 'KABUPATEN LOMBOK UTARA');
INSERT INTO `kota` VALUES ('71', '52', 'KOTA MATARAM');
INSERT INTO `kota` VALUES ('72', '52', 'KOTA BIMA');
INSERT INTO `kota` VALUES ('01', '53', 'KABUPATEN SUMBA BARAT');
INSERT INTO `kota` VALUES ('02', '53', 'KABUPATEN SUMBA TIMUR');
INSERT INTO `kota` VALUES ('03', '53', 'KABUPATEN KUPANG');
INSERT INTO `kota` VALUES ('04', '53', 'KABUPATEN TIMOR TENGAH SELATAN');
INSERT INTO `kota` VALUES ('05', '53', 'KABUPATEN TIMOR TENGAH UTARA');
INSERT INTO `kota` VALUES ('06', '53', 'KABUPATEN BELU');
INSERT INTO `kota` VALUES ('07', '53', 'KABUPATEN ALOR');
INSERT INTO `kota` VALUES ('08', '53', 'KABUPATEN LEMBATA');
INSERT INTO `kota` VALUES ('09', '53', 'KABUPATEN FLORES TIMUR');
INSERT INTO `kota` VALUES ('10', '53', 'KABUPATEN SIKKA');
INSERT INTO `kota` VALUES ('11', '53', 'KABUPATEN ENDE');
INSERT INTO `kota` VALUES ('12', '53', 'KABUPATEN NGADA');
INSERT INTO `kota` VALUES ('13', '53', 'KABUPATEN MANGGARAI');
INSERT INTO `kota` VALUES ('14', '53', 'KABUPATEN ROTE NDAO');
INSERT INTO `kota` VALUES ('15', '53', 'KABUPATEN MANGGARAI BARAT');
INSERT INTO `kota` VALUES ('16', '53', 'KABUPATEN SUMBA TENGAH');
INSERT INTO `kota` VALUES ('17', '53', 'KABUPATEN SUMBA BARAT DAYA');
INSERT INTO `kota` VALUES ('18', '53', 'KABUPATEN NAGEKEO');
INSERT INTO `kota` VALUES ('19', '53', 'KABUPATEN MANGGARAI TIMUR');
INSERT INTO `kota` VALUES ('20', '53', 'KABUPATEN SABU RAIJUA');
INSERT INTO `kota` VALUES ('21', '53', 'KABUPATEN MALAKA');
INSERT INTO `kota` VALUES ('71', '53', 'KOTA KUPANG');
INSERT INTO `kota` VALUES ('01', '61', 'KABUPATEN SAMBAS');
INSERT INTO `kota` VALUES ('02', '61', 'KABUPATEN BENGKAYANG');
INSERT INTO `kota` VALUES ('03', '61', 'KABUPATEN LANDAK');
INSERT INTO `kota` VALUES ('04', '61', 'KABUPATEN MEMPAWAH');
INSERT INTO `kota` VALUES ('05', '61', 'KABUPATEN SANGGAU');
INSERT INTO `kota` VALUES ('06', '61', 'KABUPATEN KETAPANG');
INSERT INTO `kota` VALUES ('07', '61', 'KABUPATEN SINTANG');
INSERT INTO `kota` VALUES ('08', '61', 'KABUPATEN KAPUAS HULU');
INSERT INTO `kota` VALUES ('09', '61', 'KABUPATEN SEKADAU');
INSERT INTO `kota` VALUES ('10', '61', 'KABUPATEN MELAWI');
INSERT INTO `kota` VALUES ('11', '61', 'KABUPATEN KAYONG UTARA');
INSERT INTO `kota` VALUES ('12', '61', 'KABUPATEN KUBU RAYA');
INSERT INTO `kota` VALUES ('71', '61', 'KOTA PONTIANAK');
INSERT INTO `kota` VALUES ('72', '61', 'KOTA SINGKAWANG');
INSERT INTO `kota` VALUES ('01', '62', 'KABUPATEN KOTAWARINGIN BARAT');
INSERT INTO `kota` VALUES ('02', '62', 'KABUPATEN KOTAWARINGIN TIMUR');
INSERT INTO `kota` VALUES ('03', '62', 'KABUPATEN KAPUAS');
INSERT INTO `kota` VALUES ('04', '62', 'KABUPATEN BARITO SELATAN');
INSERT INTO `kota` VALUES ('05', '62', 'KABUPATEN BARITO UTARA');
INSERT INTO `kota` VALUES ('06', '62', 'KABUPATEN SUKAMARA');
INSERT INTO `kota` VALUES ('07', '62', 'KABUPATEN LAMANDAU');
INSERT INTO `kota` VALUES ('08', '62', 'KABUPATEN SERUYAN');
INSERT INTO `kota` VALUES ('09', '62', 'KABUPATEN KATINGAN');
INSERT INTO `kota` VALUES ('10', '62', 'KABUPATEN PULANG PISAU');
INSERT INTO `kota` VALUES ('11', '62', 'KABUPATEN GUNUNG MAS');
INSERT INTO `kota` VALUES ('12', '62', 'KABUPATEN BARITO TIMUR');
INSERT INTO `kota` VALUES ('13', '62', 'KABUPATEN MURUNG RAYA');
INSERT INTO `kota` VALUES ('71', '62', 'KOTA PALANGKA RAYA');
INSERT INTO `kota` VALUES ('01', '63', 'KABUPATEN TANAH LAUT');
INSERT INTO `kota` VALUES ('02', '63', 'KABUPATEN KOTA BARU');
INSERT INTO `kota` VALUES ('03', '63', 'KABUPATEN BANJAR');
INSERT INTO `kota` VALUES ('04', '63', 'KABUPATEN BARITO KUALA');
INSERT INTO `kota` VALUES ('05', '63', 'KABUPATEN TAPIN');
INSERT INTO `kota` VALUES ('06', '63', 'KABUPATEN HULU SUNGAI SELATAN');
INSERT INTO `kota` VALUES ('07', '63', 'KABUPATEN HULU SUNGAI TENGAH');
INSERT INTO `kota` VALUES ('08', '63', 'KABUPATEN HULU SUNGAI UTARA');
INSERT INTO `kota` VALUES ('09', '63', 'KABUPATEN TABALONG');
INSERT INTO `kota` VALUES ('10', '63', 'KABUPATEN TANAH BUMBU');
INSERT INTO `kota` VALUES ('11', '63', 'KABUPATEN BALANGAN');
INSERT INTO `kota` VALUES ('71', '63', 'KOTA BANJARMASIN');
INSERT INTO `kota` VALUES ('72', '63', 'KOTA BANJAR BARU');
INSERT INTO `kota` VALUES ('01', '64', 'KABUPATEN PASER');
INSERT INTO `kota` VALUES ('02', '64', 'KABUPATEN KUTAI BARAT');
INSERT INTO `kota` VALUES ('03', '64', 'KABUPATEN KUTAI KARTANEGARA');
INSERT INTO `kota` VALUES ('04', '64', 'KABUPATEN KUTAI TIMUR');
INSERT INTO `kota` VALUES ('05', '64', 'KABUPATEN BERAU');
INSERT INTO `kota` VALUES ('09', '64', 'KABUPATEN PENAJAM PASER UTARA');
INSERT INTO `kota` VALUES ('11', '64', 'KABUPATEN MAHAKAM HULU');
INSERT INTO `kota` VALUES ('71', '64', 'KOTA BALIKPAPAN');
INSERT INTO `kota` VALUES ('72', '64', 'KOTA SAMARINDA');
INSERT INTO `kota` VALUES ('74', '64', 'KOTA BONTANG');
INSERT INTO `kota` VALUES ('01', '65', 'KABUPATEN MALINAU');
INSERT INTO `kota` VALUES ('02', '65', 'KABUPATEN BULUNGAN');
INSERT INTO `kota` VALUES ('03', '65', 'KABUPATEN TANA TIDUNG');
INSERT INTO `kota` VALUES ('04', '65', 'KABUPATEN NUNUKAN');
INSERT INTO `kota` VALUES ('71', '65', 'KOTA TARAKAN');
INSERT INTO `kota` VALUES ('01', '71', 'KABUPATEN BOLAANG MONGONDOW');
INSERT INTO `kota` VALUES ('02', '71', 'KABUPATEN MINAHASA');
INSERT INTO `kota` VALUES ('03', '71', 'KABUPATEN KEPULAUAN SANGIHE');
INSERT INTO `kota` VALUES ('04', '71', 'KABUPATEN KEPULAUAN TALAUD');
INSERT INTO `kota` VALUES ('05', '71', 'KABUPATEN MINAHASA SELATAN');
INSERT INTO `kota` VALUES ('06', '71', 'KABUPATEN MINAHASA UTARA');
INSERT INTO `kota` VALUES ('07', '71', 'KABUPATEN BOLAANG MONGONDOW UTARA');
INSERT INTO `kota` VALUES ('08', '71', 'KABUPATEN SIAU TAGULANDANG BIARO');
INSERT INTO `kota` VALUES ('09', '71', 'KABUPATEN MINAHASA TENGGARA');
INSERT INTO `kota` VALUES ('10', '71', 'KABUPATEN BOLAANG MONGONDOW SELATAN');
INSERT INTO `kota` VALUES ('11', '71', 'KABUPATEN BOLAANG MONGONDOW TIMUR');
INSERT INTO `kota` VALUES ('71', '71', 'KOTA MANADO');
INSERT INTO `kota` VALUES ('72', '71', 'KOTA BITUNG');
INSERT INTO `kota` VALUES ('73', '71', 'KOTA TOMOHON');
INSERT INTO `kota` VALUES ('74', '71', 'KOTA KOTAMOBAGU');
INSERT INTO `kota` VALUES ('01', '72', 'KABUPATEN BANGGAI KEPULAUAN');
INSERT INTO `kota` VALUES ('02', '72', 'KABUPATEN BANGGAI');
INSERT INTO `kota` VALUES ('03', '72', 'KABUPATEN MOROWALI');
INSERT INTO `kota` VALUES ('04', '72', 'KABUPATEN POSO');
INSERT INTO `kota` VALUES ('05', '72', 'KABUPATEN DONGGALA');
INSERT INTO `kota` VALUES ('06', '72', 'KABUPATEN TOLI-TOLI');
INSERT INTO `kota` VALUES ('07', '72', 'KABUPATEN BUOL');
INSERT INTO `kota` VALUES ('08', '72', 'KABUPATEN PARIGI MOUTONG');
INSERT INTO `kota` VALUES ('09', '72', 'KABUPATEN TOJO UNA-UNA');
INSERT INTO `kota` VALUES ('10', '72', 'KABUPATEN SIGI');
INSERT INTO `kota` VALUES ('11', '72', 'KABUPATEN BANGGAI LAUT');
INSERT INTO `kota` VALUES ('12', '72', 'KABUPATEN MOROWALI UTARA');
INSERT INTO `kota` VALUES ('71', '72', 'KOTA PALU');
INSERT INTO `kota` VALUES ('01', '73', 'KABUPATEN KEPULAUAN SELAYAR');
INSERT INTO `kota` VALUES ('02', '73', 'KABUPATEN BULUKUMBA');
INSERT INTO `kota` VALUES ('03', '73', 'KABUPATEN BANTAENG');
INSERT INTO `kota` VALUES ('04', '73', 'KABUPATEN JENEPONTO');
INSERT INTO `kota` VALUES ('05', '73', 'KABUPATEN TAKALAR');
INSERT INTO `kota` VALUES ('06', '73', 'KABUPATEN GOWA');
INSERT INTO `kota` VALUES ('07', '73', 'KABUPATEN SINJAI');
INSERT INTO `kota` VALUES ('08', '73', 'KABUPATEN MAROS');
INSERT INTO `kota` VALUES ('09', '73', 'KABUPATEN PANGKAJENE DAN KEPULAUAN');
INSERT INTO `kota` VALUES ('10', '73', 'KABUPATEN BARRU');
INSERT INTO `kota` VALUES ('11', '73', 'KABUPATEN BONE');
INSERT INTO `kota` VALUES ('12', '73', 'KABUPATEN SOPPENG');
INSERT INTO `kota` VALUES ('13', '73', 'KABUPATEN WAJO');
INSERT INTO `kota` VALUES ('14', '73', 'KABUPATEN SIDENRENG RAPPANG');
INSERT INTO `kota` VALUES ('15', '73', 'KABUPATEN PINRANG');
INSERT INTO `kota` VALUES ('16', '73', 'KABUPATEN ENREKANG');
INSERT INTO `kota` VALUES ('17', '73', 'KABUPATEN LUWU');
INSERT INTO `kota` VALUES ('18', '73', 'KABUPATEN TANA TORAJA');
INSERT INTO `kota` VALUES ('22', '73', 'KABUPATEN LUWU UTARA');
INSERT INTO `kota` VALUES ('25', '73', 'KABUPATEN LUWU TIMUR');
INSERT INTO `kota` VALUES ('26', '73', 'KABUPATEN TORAJA UTARA');
INSERT INTO `kota` VALUES ('71', '73', 'KOTA MAKASSAR');
INSERT INTO `kota` VALUES ('72', '73', 'KOTA PAREPARE');
INSERT INTO `kota` VALUES ('73', '73', 'KOTA PALOPO');
INSERT INTO `kota` VALUES ('01', '74', 'KABUPATEN BUTON');
INSERT INTO `kota` VALUES ('02', '74', 'KABUPATEN MUNA');
INSERT INTO `kota` VALUES ('03', '74', 'KABUPATEN KONAWE');
INSERT INTO `kota` VALUES ('04', '74', 'KABUPATEN KOLAKA');
INSERT INTO `kota` VALUES ('05', '74', 'KABUPATEN KONAWE SELATAN');
INSERT INTO `kota` VALUES ('06', '74', 'KABUPATEN BOMBANA');
INSERT INTO `kota` VALUES ('07', '74', 'KABUPATEN WAKATOBI');
INSERT INTO `kota` VALUES ('08', '74', 'KABUPATEN KOLAKA UTARA');
INSERT INTO `kota` VALUES ('09', '74', 'KABUPATEN BUTON UTARA');
INSERT INTO `kota` VALUES ('10', '74', 'KABUPATEN KONAWE UTARA');
INSERT INTO `kota` VALUES ('11', '74', 'KABUPATEN KOLAKA TIMUR');
INSERT INTO `kota` VALUES ('12', '74', 'KABUPATEN KONAWE KEPULAUAN');
INSERT INTO `kota` VALUES ('13', '74', 'KABUPATEN MUNA BARAT');
INSERT INTO `kota` VALUES ('14', '74', 'KABUPATEN BUTON TENGAH');
INSERT INTO `kota` VALUES ('15', '74', 'KABUPATEN BUTON SELATAN');
INSERT INTO `kota` VALUES ('71', '74', 'KOTA KENDARI');
INSERT INTO `kota` VALUES ('72', '74', 'KOTA BAUBAU');
INSERT INTO `kota` VALUES ('01', '75', 'KABUPATEN BOALEMO');
INSERT INTO `kota` VALUES ('02', '75', 'KABUPATEN GORONTALO');
INSERT INTO `kota` VALUES ('03', '75', 'KABUPATEN POHUWATO');
INSERT INTO `kota` VALUES ('04', '75', 'KABUPATEN BONE BOLANGO');
INSERT INTO `kota` VALUES ('05', '75', 'KABUPATEN GORONTALO UTARA');
INSERT INTO `kota` VALUES ('71', '75', 'KOTA GORONTALO');
INSERT INTO `kota` VALUES ('01', '76', 'KABUPATEN MAJENE');
INSERT INTO `kota` VALUES ('02', '76', 'KABUPATEN POLEWALI MANDAR');
INSERT INTO `kota` VALUES ('03', '76', 'KABUPATEN MAMASA');
INSERT INTO `kota` VALUES ('04', '76', 'KABUPATEN MAMUJU');
INSERT INTO `kota` VALUES ('05', '76', 'KABUPATEN MAMUJU UTARA');
INSERT INTO `kota` VALUES ('06', '76', 'KABUPATEN MAMUJU TENGAH');
INSERT INTO `kota` VALUES ('01', '81', 'KABUPATEN MALUKU TENGGARA BARAT');
INSERT INTO `kota` VALUES ('02', '81', 'KABUPATEN MALUKU TENGGARA');
INSERT INTO `kota` VALUES ('03', '81', 'KABUPATEN MALUKU TENGAH');
INSERT INTO `kota` VALUES ('04', '81', 'KABUPATEN BURU');
INSERT INTO `kota` VALUES ('05', '81', 'KABUPATEN KEPULAUAN ARU');
INSERT INTO `kota` VALUES ('06', '81', 'KABUPATEN SERAM BAGIAN BARAT');
INSERT INTO `kota` VALUES ('07', '81', 'KABUPATEN SERAM BAGIAN TIMUR');
INSERT INTO `kota` VALUES ('08', '81', 'KABUPATEN MALUKU BARAT DAYA');
INSERT INTO `kota` VALUES ('09', '81', 'KABUPATEN BURU SELATAN');
INSERT INTO `kota` VALUES ('71', '81', 'KOTA AMBON');
INSERT INTO `kota` VALUES ('72', '81', 'KOTA TUAL');
INSERT INTO `kota` VALUES ('01', '82', 'KABUPATEN HALMAHERA BARAT');
INSERT INTO `kota` VALUES ('02', '82', 'KABUPATEN HALMAHERA TENGAH');
INSERT INTO `kota` VALUES ('03', '82', 'KABUPATEN KEPULAUAN SULA');
INSERT INTO `kota` VALUES ('04', '82', 'KABUPATEN HALMAHERA SELATAN');
INSERT INTO `kota` VALUES ('05', '82', 'KABUPATEN HALMAHERA UTARA');
INSERT INTO `kota` VALUES ('06', '82', 'KABUPATEN HALMAHERA TIMUR');
INSERT INTO `kota` VALUES ('07', '82', 'KABUPATEN PULAU MOROTAI');
INSERT INTO `kota` VALUES ('08', '82', 'KABUPATEN PULAU TALIABU');
INSERT INTO `kota` VALUES ('71', '82', 'KOTA TERNATE');
INSERT INTO `kota` VALUES ('72', '82', 'KOTA TIDORE KEPULAUAN');
INSERT INTO `kota` VALUES ('01', '91', 'KABUPATEN FAKFAK');
INSERT INTO `kota` VALUES ('02', '91', 'KABUPATEN KAIMANA');
INSERT INTO `kota` VALUES ('03', '91', 'KABUPATEN TELUK WONDAMA');
INSERT INTO `kota` VALUES ('04', '91', 'KABUPATEN TELUK BINTUNI');
INSERT INTO `kota` VALUES ('05', '91', 'KABUPATEN MANOKWARI');
INSERT INTO `kota` VALUES ('06', '91', 'KABUPATEN SORONG SELATAN');
INSERT INTO `kota` VALUES ('07', '91', 'KABUPATEN SORONG');
INSERT INTO `kota` VALUES ('08', '91', 'KABUPATEN RAJA AMPAT');
INSERT INTO `kota` VALUES ('09', '91', 'KABUPATEN TAMBRAUW');
INSERT INTO `kota` VALUES ('10', '91', 'KABUPATEN MAYBRAT');
INSERT INTO `kota` VALUES ('11', '91', 'KABUPATEN MANOKWARI SELATAN');
INSERT INTO `kota` VALUES ('12', '91', 'KABUPATEN PEGUNUNGAN ARFAK');
INSERT INTO `kota` VALUES ('71', '91', 'KOTA SORONG');
INSERT INTO `kota` VALUES ('01', '94', 'KABUPATEN MERAUKE');
INSERT INTO `kota` VALUES ('02', '94', 'KABUPATEN JAYAWIJAYA');
INSERT INTO `kota` VALUES ('03', '94', 'KABUPATEN JAYAPURA');
INSERT INTO `kota` VALUES ('04', '94', 'KABUPATEN NABIRE');
INSERT INTO `kota` VALUES ('08', '94', 'KABUPATEN KEPULAUAN YAPEN');
INSERT INTO `kota` VALUES ('09', '94', 'KABUPATEN BIAK NUMFOR');
INSERT INTO `kota` VALUES ('10', '94', 'KABUPATEN PANIAI');
INSERT INTO `kota` VALUES ('11', '94', 'KABUPATEN PUNCAK JAYA');
INSERT INTO `kota` VALUES ('12', '94', 'KABUPATEN MIMIKA');
INSERT INTO `kota` VALUES ('13', '94', 'KABUPATEN BOVEN DIGOEL');
INSERT INTO `kota` VALUES ('14', '94', 'KABUPATEN MAPPI');
INSERT INTO `kota` VALUES ('15', '94', 'KABUPATEN ASMAT');
INSERT INTO `kota` VALUES ('16', '94', 'KABUPATEN YAHUKIMO');
INSERT INTO `kota` VALUES ('17', '94', 'KABUPATEN PEGUNUNGAN BINTANG');
INSERT INTO `kota` VALUES ('18', '94', 'KABUPATEN TOLIKARA');
INSERT INTO `kota` VALUES ('19', '94', 'KABUPATEN SARMI');
INSERT INTO `kota` VALUES ('20', '94', 'KABUPATEN KEEROM');
INSERT INTO `kota` VALUES ('26', '94', 'KABUPATEN WAROPEN');
INSERT INTO `kota` VALUES ('27', '94', 'KABUPATEN SUPIORI');
INSERT INTO `kota` VALUES ('28', '94', 'KABUPATEN MAMBERAMO RAYA');
INSERT INTO `kota` VALUES ('29', '94', 'KABUPATEN NDUGA');
INSERT INTO `kota` VALUES ('30', '94', 'KABUPATEN LANNY JAYA');
INSERT INTO `kota` VALUES ('31', '94', 'KABUPATEN MAMBERAMO TENGAH');
INSERT INTO `kota` VALUES ('32', '94', 'KABUPATEN YALIMO');
INSERT INTO `kota` VALUES ('33', '94', 'KABUPATEN PUNCAK');
INSERT INTO `kota` VALUES ('34', '94', 'KABUPATEN DOGIYAI');
INSERT INTO `kota` VALUES ('35', '94', 'KABUPATEN INTAJAYA');
INSERT INTO `kota` VALUES ('36', '94', 'KABUPATEN DEIYAI');
INSERT INTO `kota` VALUES ('71', '94', 'KOTA JAYAPURA');



